# fly.toml app configuration file generated for ecoride-bold-sky-2587
app = "ecoride-bold-sky-2587"
primary_region = "lhr"

[build]

[env]
  PORT = "8080"
  DB_HOST = "***REMOVED***"
  DB_PORT = "32252"
  DB_DATABASE = "***REMOVED***"
  DB_USERNAME = "***REMOVED***"
  DB_PASSWORD = "***REMOVED***"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1